---
kind: ConfigMap
apiVersion: v1
metadata:
  name: infoblox-cni-cfg
  namespace: kube-system
  labels:
    tier: node
    app: infoblox-cni-cfg
data:
  ipam_conf_file_name: infoblox-ipam.conf
  ## Network Config file contents##
  ##This key should match the value of the key 'ipam_conf_file_name'##
  infoblox-ipam.conf: |
    {
    "name": "ipam-test",
    "type": "macvlan",
    "master":"eth0",
    "ipam": {
        "type": "infoblox",
        "subnet": "10.0.0.0/24",
        "gateway":"10.0.0.1",
        "network-view": "cni_view"
        }
    }
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: infoblox-cni-install
  namespace: kube-system
  labels:
    tier: node
    k8s-app: infoblox-cni-install
spec:
  selector:
      matchLabels:
        name: infoblox-cni-install
  template:
    metadata:
      labels:
        name: infoblox-cni-install
    spec:
      containers:
      - name: install-cni
        image: infoblox/infoblox-cni-install
        lifecycle:
              preStop:
                   exec:
                     command:
                        - sh
                        - "-c"
                        - "rm -rf /host/opt/cni/bin/infoblox /host/etc/cni/net.d/ipam_conf_file_name /host/etc/cni/net.d/${CONF_FILE_NAME}"
        env:
        - name: CONF_FILE_NAME
          valueFrom:
                configMapKeyRef:
                   name: infoblox-cni-cfg
                   key: ipam_conf_file_name
        command: [ "/install/install-cni.sh" ]
        volumeMounts:
        - name: conf-loc
          mountPath: /install/config
        - name: host-cni-conf
          mountPath: /host/etc/cni/net.d/
        - name: host-cni-bin
          mountPath: /host/opt/cni/bin/
      hostNetwork: true
      volumes:
        - name: conf-loc
          configMap:
                name: infoblox-cni-cfg
        - name: host-cni-conf
          hostPath:
            path: /etc/cni/net.d
        - name: host-cni-bin
          hostPath:
            path: /opt/cni/bin
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
